apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: llmmll-models
  namespace: llmmll
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path