# Code generated by schema2code at 2025-12-01 22:31:33. DO NOT EDIT.


from typing import List, Dict, Optional, Any, Union, Annotated, Literal
from datetime import datetime, date, time, timedelta
from pydantic import BaseModel, ConfigDict, Field, AnyUrl, EmailStr, conint, confloat



class PreferencesConfig(BaseModel):
    """User preferences"""
    default_profile_id: Annotated[Optional[str], Field(default=None, description="Default profile ID")] = None
    """Default profile ID"""
    theme: Annotated[Optional[str], Field(default=None, description="Theme")] = None
    """Theme"""
    font_size: Annotated[Optional[int], Field(default=None, description="Font size")] = None
    """Font size"""
    notifications_on: Annotated[Optional[bool], Field(default=None, description="Notifications enabled")] = None
    """Notifications enabled"""
    language: Annotated[Optional[str], Field(default=None, description="Language")] = None
    """Language"""

    model_config = ConfigDict(extra="ignore")